_target_: lfads_torch.datamodules.BasicDataModule
datafile_pattern: "/results/mesoscale_lfads_data/sub-455219/sub-455219_ses-20190808T140448_lfads.h5"
attr_keys:
  - train_trial_idx
  - valid_trial_idx
batch_size: 128
