_target_: lfads_torch.datamodules.BasicDataModule
datafile_pattern: "/results/mesoscale_lfads_data/sub-480135/sub-480135_ses-20210225T155426_lfads.h5"
attr_keys:
  - train_trial_idx
  - valid_trial_idx
batch_size: 64
